import sys
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from config.settings import EMAIL_DELIVERY_CONFIG


class EmailDelivery:
    """Send daily briefs via email."""
    
    def __init__(self):
        self.config = EMAIL_DELIVERY_CONFIG or {}
        
    def send_brief(self, brief_text: str, recipient_email: str, 
                   subject: str = "📬 Your Daily Email Brief") -> bool:
        """
        Send daily brief via email.
        
        Args:
            brief_text: The brief content
            recipient_email: Email address to send to
            subject: Email subject line
            
        Returns:
            True if sent successfully, False otherwise
        """
        if not self.config.get('enabled', False):
            return False
            
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.config.get('from_email', 'noreply@dailybrief.local')
            msg['To'] = recipient_email
            
            # Create HTML version
            html_brief = self._format_brief_html(brief_text)
            
            # Create plain text version
            text_part = MIMEText(brief_text, 'plain')
            html_part = MIMEText(html_brief, 'html')
            
            msg.attach(text_part)
            msg.attach(html_part)
            
            # Send email
            if self.config.get('smtp_server'):
                self._send_via_smtp(msg, recipient_email)
            else:
                # Use Gmail API if configured
                self._send_via_gmail_api(msg, recipient_email)
            
            return True
            
        except Exception as e:
            print(f"Error sending email: {e}")
            return False
    
    def _format_brief_html(self, brief_text: str) -> str:
        """Format brief as HTML."""
        lines = brief_text.split('\n')
        html = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; 
                       line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
                h1 { color: #1e3c72; border-bottom: 3px solid #f5a623; padding-bottom: 10px; }
                .email-item { background: #f8f9fa; padding: 15px; margin: 15px 0; 
                             border-left: 4px solid #2a5298; border-radius: 4px; }
                .score { color: #f5a623; font-weight: bold; }
                .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; 
                         color: #666; font-size: 12px; }
            </style>
        </head>
        <body>
        """
        
        for line in lines:
            if line.startswith('='):
                html += f"<hr>"
            elif line.startswith('📬'):
                html += f"<h1>{line}</h1>"
            elif line.startswith('From:') or line.startswith('Subject:'):
                html += f"<p><strong>{line}</strong></p>"
            elif line.strip():
                html += f"<p>{line}</p>"
            else:
                html += "<br>"
        
        html += """
            <div class="footer">
                <p>This brief was generated by Daily Email Brief.</p>
                <p>To adjust your preferences, run: python main.py preferences</p>
            </div>
        </body>
        </html>
        """
        
        return html
    
    def _send_via_smtp(self, msg: MIMEMultipart, recipient: str):
        """Send email via SMTP."""
        smtp_server = self.config.get('smtp_server')
        smtp_port = self.config.get('smtp_port', 587)
        username = self.config.get('smtp_username')
        password = self.config.get('smtp_password')
        
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(username, password)
            server.send_message(msg)
    
    def _send_via_gmail_api(self, msg: MIMEMultipart, recipient: str):
        """Send email via Gmail API (if user has send permissions)."""
        # This would require additional Gmail API setup with send permissions
        # For now, we'll use SMTP
        raise NotImplementedError("Gmail API sending not yet implemented. Use SMTP instead.")
