#!/bin/bash
echo "=== Checking what will be ignored ==="
echo ""
echo "Sensitive files that should be ignored:"
echo "  ✅ .env files"
echo "  ✅ node_modules/"
echo "  ✅ uploads/ (user data)"
echo "  ✅ dist/ (build output)"
echo "  ✅ *.log files"
echo "  ✅ .replit files"
echo "  ✅ Docker volumes (postgres_data/)"
echo ""
echo "To verify, run:"
echo "  git status --ignored"
echo ""
echo "To see what would be committed:"
echo "  git status"
